# Generated by Django 3.2 on 2022-11-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221118_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=255)),
                ('Full_Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Total_Price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Order Table',
            },
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Single_Price', models.IntegerField()),
                ('Subtotal_Price', models.IntegerField()),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.color')),
                ('Embroidery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.embroidery')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_table')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.size')),
            ],
            options={
                'verbose_name_plural': 'Order Table',
            },
        ),
    ]
